app/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('about/', views.about, name = 'about'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('profile/', views.profile, name = 'profile'),
    path('register/', views.register, name = 'register'),
    path('tables/', views.table, name = 'table'),
]

blog/models.py
from django.db import models



class Index(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название')
    images = models.ImageField(upload_to = 'ins_images', blank = True, null = True, verbose_name = 'Изображение в картах')
    text = models.TextField(verbose_name='Текст в картах')

    class Meta:
        verbose_name = 'информацию в картах'
        verbose_name_plural = 'Информация в картах'


    def __str__(self):
        return self.name



class Accord(models.Model):
    name = models.CharField(max_length = 100, verbose_name = 'Заголовок')
    text = models.TextField(verbose_name = 'Текст аккордиона')

    class Meta:
        verbose_name = 'текст аккордиона'
        verbose_name_plural = 'Тексты аккордиона'

    def __str__(self):
        return self.name


class About(models.Model):
    name = models.CharField(max_length = 100, verbose_name = 'Заголовок')
    text = models.TextField(verbose_name = 'Текст')

    class Meta:
        verbose_name = 'текст о нас'
        verbose_name_plural = 'Тексты о нас'

    def __str__(self):
        return self.name



class Carousel(models.Model):
    images = models.ImageField(upload_to = 'ins_images', blank = True, null = True, verbose_name = 'Изображение в карусели:')
    text = models.TextField(verbose_name='Текст в карусели:')

    class Meta:
        verbose_name = 'анонс в слайдере'
        verbose_name_plural = 'Анонсы в слайдере'


    def __str__(self):
        return self.text

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to = 'users_images', blank = True, null = True, verbose_name = 'Аватар')


    class Meta:
        db_table = 'user'
        verbose_name = 'пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()
          
    class Meta:
        model = User


class UserRegistrationForm(UserCreationForm):
    
    class Meta:
        model=User
        fields=(
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        )
        
    first_name=forms.CharField()
    last_name=forms.CharField()
    username=forms.CharField()
    email=forms.CharField()
    password1=forms.CharField()
    password2=forms.CharField()


class ProfileForm(UserChangeForm):
    
    class Meta:
        model=User
        fields=(
            'image',
            'first_name',
            'last_name',
            'username',
            'email',)
        
    image=forms.ImageField(required=False)
    first_name=forms.CharField()
    last_name=forms.CharField()
    username=forms.CharField()
    email=forms.CharField()

blog/views.py
from django.shortcuts import render

from .models import Index, Accord, About, Carousel



def index(request):
    form = Index.objects.order_by('-id')[:6]
    accord = Accord.objects.order_by('-id')

    context = {
        'title': 'Страховая компания',
        'form': form,
        'accord': accord
    }

    return render(request, 'blog/index.html', context)


def about(request):
    carousel = Carousel.objects.all()
    forms = About.objects.order_by('-id')

    context = {
        'title': 'О нас',
        'forms': forms,
        'carousel': carousel,
    }

    return render(request, 'blog/about.html', context)

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.contrib import auth, messages
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Prefetch
from django.views.generic import CreateView, UpdateView
from django.views.generic import TemplateView


from users.models import User
from users.forms import UserLoginForm, UserRegistrationForm, ProfileForm


def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data = request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username = username, password = password)
            if user:
                auth.login(request, user)
                messages.success(request, f'{username}, Вы вошли в аккаунт')
                return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = UserLoginForm()

    context = { 
            'title': "Авторизация",
            'form': form
        }

    return render(request, 'users/login.html', context)


def register(request):
   
    if request.method=='POST':
        form=UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            
            session_key=request.session.session_key
            
            user=form.instance
            auth.login(request, user)
            
            # if session_key:
            #     User.objects.filter(session_key=session_key).update(user=user)
            
            messages.success(request, f'{user.username}, Вы успешно зарегистрированы и вошли в аккаунт!')
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form=UserRegistrationForm()
        
    context={
        'title': 'Регистрация',
        'form': form
    }
    return render(request, 'users/register.html', context)



@login_required
def profile(request):
    if request.method=='POST':
        form = ProfileForm(data=request.POST, instance = request.user, files = request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, f'Профиль успешно обновлен!')
            return HttpResponseRedirect(reverse('users:profile'))
    else:
        form = ProfileForm(instance = request.user)

    context = {
        'title': "Кабинет",
        'form': form
    }

    return render(request, 'users/profile.html', context)

@login_required
def logout(request):
    messages.success(request, f'{request.user.username}, Вы вышли из аккаунта.')
    auth.logout(request)
    return redirect(reverse('users:login'))



def table(request):
    forms = User.objects.order_by('last_name').values()

    context = {
        'title': 'Данные пользователей.',
        'forms': forms,
    }

    return render(request, 'users/tables.html', context)

templates/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="{% static 'deps/css/nav.css' %}" />
    <link rel="stylesheet" href="{% static 'deps/css/about.css' %}" />
    <link rel="stylesheet" href="{% static 'deps/css/section.css' %}" />
    <link rel="stylesheet" href="{% static 'deps/css/footer.css' %}" />
    <link rel="stylesheet" href="{% static 'deps/css/table.css' %}" />
    <title>Document</title>
  </head>
  <body>
    <header>
      <div class="nav-bars">
        <a href="{% url 'blog:index' %}"><img src="{% static 'deps/images/Ferrari-SF90-Stradale-PNG-Image-Background.png' %}" alt="" /></a>
        <div class="drop">
          <button class="btns">&#9776;</button>
          <div class="nav-list">
            <a href="{% url 'blog:index' %}">Главная</a>
            <a href="{% url 'blog:about' %}">О нас</a>
            <a href="{% url 'users:table' %}">Данные</a>

            <div class="btn-group">
              <button type="button" class="btn btn-danger dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">Профиль</button>
              <ul class="dropdown-menu">
                {% if not user.is_authenticated %}
                  <li>
                    <a class="dropdown-item" href="{% url 'users:login' %}">Войти</a>
                  </li>
                {% else %}
                    <li>
                      <a class="dropdown-item" href="{% url 'users:profile' %}">Мой профиль</a>
                    </li>
                    {% if user.is_admin or user.is_staff %}
                      <li>
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Админ панель</a>
                      </li>
                    {% endif %}
                    <li>
                      <hr class="dropdown-divider" />
                    </li>
                    <li>
                      <a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </header>

    <section>
      <div class="container-fluid index">
        <div class="row">
          <div class="index-img">
            {% block img %}
              <img src="{% static 'deps/images/erp.png' %}" alt="" />
            {% endblock %}
            <div class="col-lg-4 col-md-12 text-img">
              <h1>Страховая компания</h1>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam error consequatur qui modi? Odio, eligendi! Quia assumenda possimus omnis quas aliquid cum deserunt commodi maiores!</p>
            </div>
          </div>
          {% include "includes/notifications.html" %}
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </section>

    <footer>
      <div class="container-fluid footer">
        <div class="row">
          <div class="col-lg-4 col-md-12">
            <div class="row">
              <h6>Частная страховая компания</h6>
            </div>
          </div>
          <div class="col-lg-4 col-md-12">
            <div class="row">
              <h6>Работа<br />Адреса<br />Контакты</h6>
            </div>
          </div>
          <div class="col-lg-4 col-md-12">
            <div class="row">
              <div class="foot-img">
                <a href=""><img src="{% static 'deps/icons/icons8-телеграмма-app.gif' %}" alt="" /></a>
                <a href=""><img src="{% static 'deps/icons/icons8-whatsapp.gif' %}" alt="" /></a>
                <a href=""><img src="{% static 'deps/icons/telephone.png' %}" alt="" /></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'deps/js/myjs.js' %}"></script>
  </body>
</html>

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block img %}
  <img src="{% static 'deps/images/w_dfe2096d.jpg' %}" alt="" />
{% endblock %}
{% block content %}
  <div class="row">
    <div class="container mt-5 log">
      <div class="row justify-content-center">
        <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
          <h2 class="text-center mb-4">Авторизация</h2>
          <form action="{% url 'users:login' %}" method="post">
            {% csrf_token %}

            <div class="mb-3">
              <label for="id_username" class="form-label">Имя пользователя</label>
              <input type="text" class="form-control" value="{% if form.username.value %}{{ form.username.value }}{% endif %}" name="username" id="id_username" placeholder="Введите ваше имя пользователя" required />
            </div>
            <div class="mb-3">
              <label for="id_password" class="form-label">Пароль</label>
              <input type="password" class="form-control" name="password" id="id_password" placeholder="Введите ваш пароль" required />
            </div>

        
            <button type="submit" class="btn btn-dark btn-block">Войти</button>
          </form>
          <div class="mt-3">
            <a href="{% url 'users:register' %}">Создать аккаунт</a>
          </div>
          <hr />
        </div>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block img %}
    <img src="{% static 'deps/images/cyber-security.jpg' %}" alt="">
{% endblock img %}


{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row">
            <!-- Профиль с данными пользователя -->
            <div class="col-md-5 proff">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Профиль пользователя</h3>
                    <form action="{% url 'users:profile' %}" method="post" enctype = "multipart/form-data">
                    {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 mb-3 text-center">
                                {% if user.image %}
                                    <img src="{{ user.image.url }}"
                                    alt="Аватар пользователя" class="img-fluid rounded-circle"
                                    style="max-width: 150px;">
                                {% else %}
                                    <img src="{% static 'deps/images/baseavatar.jpg' %}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                {% endif %}
                                <input type="file" class="form-control mt-3" id="id_image"
                                name = "image"
                                    accept="image/*">
                                {% if form.image.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.image.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_first_name" class="form-label">Имя*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                name = "first_name"
                                    placeholder="Введите ваше имя" 
                                    value="{{ form.first_name.value }}" required>
                                {% if form.first_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                name = "last_name"
                                    placeholder="Введите вашу фамилию" 
                                    value="{{ form.last_name.value }}" required>
                                    
                                {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input type="text" class="form-control" id="id_username"
                                name = "username"
                                    placeholder="Введите ваше имя пользователя" 
                                    value="{{ form.username.value }}" required>
                                {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                name = "email"
                                    placeholder="Введите ваш email *youremail@example.com" 
                                    value="{{ form.email.value }}"
                                    required>
                                {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                {% endif %}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Сохранить</button>
                    </form>
                </div>
            </div>
            <!-- Корзина -->
            <div class="col-md-7 corz">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Корзина</h3>
                    <div class="container" id="cart-items-container">
                        <!-- Разметка корзины -->
                        <div class="card mb-3 text-bg-light shadow-lg">
                            <div class="card-header">
                                <h5 class="card-title">Товар</h5>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                    <div class="row text-center">
                                        <div class="col p-0">
                                            <div class="input-group">
                                                <span class="input-group-btn">
                                                    <button type="button" class="btn btn-dark btn-sm decrement"
                                                        data-cart-id="" data-cart-change-url="">-</button>
                                                </span>
                                                <input type="text" class="form-control number" value="1"
                                                    readonly>
                                                <span class="input-group-btn">
                                                    <button type="button" class="btn btn-dark btn-sm increment"
                                                        data-cart-id="" data-cart-change-url="">+</button>
                                                </span>
                                            </div>
                                        </div>
                                        <div class="col p-0">
                                            <p>x 100.00 = </p>
                                        </div>
                                        <div class="col p-0"><strong>100.00 $</strong></div>
                                        <div class="col p-0">
                                            <a href="#" class="remove-from-cart" data-cart-id="">
                                                <img class="mx-1" src="{% static 'deps/icons/trash3-fill.svg' %}"
                                                    alt="Catalog Icon" width="16" height="16">
                                            </a>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <div class="card mb-3 shadow-lg">
                            <div class="card-footer">
                                <p class="float-left">Итого <strong>1</strong> товар(а) на сумму</p>
                                <h4 class="float-left"><strong>100.00 $</strong></h4>
                            </div>
                        </div>
                        <!-- Закончилась разметка корзины -->
                    </div>
                    <a class="btn btn-dark" href="{% static 'orders/create_order.html' %}">
                        Оформить заказ
                    </a>
                </div>
            </div>
            <!-- Оформленные заказы -->
            <div class="col-md-11 orders">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Мои заказы</h3>
                    <!-- Разметка заказов -->
                    <div class="container">
                        <div class="accordion" id="accordionExample">
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading1">
                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapse1">
                                        Заказ № 256 - 09 сентября 2023 9:04 | Статус:<strong class="mx-2"> В обработке</strong>
                                    </button>
                                </h2>
                                <div id="collapse1" class="accordion-collapse collapse show" aria-labelledby="heading1" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Количество</th>
                                                    <th>Цена</th>
                                                    <th>Общая стоимость</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td><a class="text-white" href="#">Комплект стол и три стула</a></td>
                                                    <td>1</td>
                                                    <td>255.00 $</td>
                                                    <td>255.00 $</td>
                                                    
                                                </tr>
                                            </tbody>
                                        </table>
                                        <div class="d-flex justify-content-between">
                                            <p><strong>Итого:</strong></p>
                                            <p><strong>255.00 $</strong></p>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading2">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse2" aria-expanded="false" aria-controls="collapse2">
                                        Заказ № 248 - 01 августа 2023 11:28 | Статус: <strong>Получен</strong>
                                    </button>
                                </h2>
                                <div id="collapse2" class="accordion-collapse collapse" aria-labelledby="heading2" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Товар</th>
                                                    <th>Количество</th>
                                                    <th>Цена</th>
                                                    <th>Общая стоимость</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td><a class="text-white" href="#">Стул офисный</a></td>
                                                    <td>2</td>
                                                    <td>30.00 $</td>
                                                    <td>60.00 $</td>
                                                    
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Закончилась разметка заказов -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load static %}

{% block img %}
    <img src="{% static 'deps/images/fb65f587e9d45b448c4e225aad0db046.jpg' %}" alt="">
{% endblock img %}



{% block content %}
<div class="row">
    <div class="container mt-5 register">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Регистрация</h2>
                <form action = "{% url 'users:register' %}" method = "post">
                {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Имя*</label>
                            <input type="text" class="form-control" id="id_first_name"
                            value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                            name = "first_name"
                                placeholder="Введите ваше имя" required>
                            {% if form.first_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                            {% endif %}

                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Фамилия*</label>
                            <input type="text" class="form-control" id="id_last_name"
                            value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                            name = "last_name"
                                placeholder="Введите вашу фамилию" required>
                            {% if form.last_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                            {% endif %}

                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_username" class="form-label">Имя пользователя*</label>
                            <input type="text" class="form-control" id="id_username"
                            value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                            name = "username"
                                placeholder="Введите ваше имя пользователя" required>
                            {% if form.username.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                            {% endif %}

                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email*</label>
                            <input type="email" class="form-control" id="id_email"
                            value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                            name = "email"
                                placeholder="Введите ваш email" required>
                            {% if form.email.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                            {% endif %}

                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label">Пароль*</label>
                            <input type="password" class="form-control" id="id_password1"
                            value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                            name = "password1"
                                placeholder="Введите пароль" required>
                            {% if form.password1.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                            {% endif %}

                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                            <input type="password" class="form-control" id="id_password2"
                            value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                            name = "password2"
                                placeholder="Подтвердите пароль" required>
                            {% if form.password2.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                            {% endif %}
                        </div>
                    </div>
                    <button type="submit"
                        class="btn btn-dark btn-block">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}